# A compose file for development.
version: '2'
services:
  demo-geomapfish-print:
    image: demo-geomapfish-print:latest
    links:
      - mapserver
    ports:
      - 8280:8080

  demo-geomapfish-mapserver:
    image: demo-geomapfish-mapserver:latest
    ports:
      - 8380:80

  demo-geomapfish-wsgi:
    image: demo-geomapfish-wsgi:latest
    links:
      - mapserver
    ports:
      - 8480:80
