{{- if eq .Values.clusterType "openshift" -}}
  {{ $root := . }}
apiVersion: {{ template "geomapfish.api_version" . }}
items:
  {{- range $key, $value := .Values.apps }}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: {{ template "geomapfish.fullname" $root }}-{{ $key }}
    labels:
      {{- include "geomapfish.release_labels" $root | indent 6 }}
  spec:
    replicas: {{ $value.replicas }}
    selector:
      {{- include "geomapfish.release_labels" $root | indent 6 }}
    strategy:
      resources: {}
    template:
      metadata:
        labels:
          {{- include "geomapfish.release_labels" $root | indent 10 }}
      spec:
        containers:
        - name: {{ template "geomapfish.fullname" $root }}-{{ $key }}
          image: {{ $root.Values.registry.host }}:{{ $root.Values.registry.port }}/{{ $root.Values.registry.namespace }}/{{ template "geomapfish.name" $root }}-print:{{ $root.Values.imageTag }}
          ports:
          - containerPort: {{ $value.port }}
    {{- if $value.dbEnvs }}
      {{- include "geomapfish.db_envs" $root | indent 10 }}
    {{- end }}
          resources: {}
        restartPolicy: Always
    test: false
    triggers: {}
  {{- end }}
kind: List
{{- end }}