{{- if eq .Values.clusterType "openshift" -}}
{{ $root := . }}
apiVersion: v1
items:
  {{- range $key, $value := .Values.apps }}
- apiVersion: {{ template "geomapfish.api_version" $root }}
  kind: DeploymentConfig
  metadata:
    name: {{ template "geomapfish.fullname" $root }}-{{ $key }}
    labels:
      name: {{ template "geomapfish.fullname" $root }}-{{ $key }}
      {{- include "geomapfish.release_labels" $root | indent 6 }}
  spec:
    replicas: {{ $value.replicas }}
    strategy:
      resources: {}
    template:
      metadata:
        labels:
          name: {{ template "geomapfish.fullname" $root }}-{{ $key }}
      spec:
        containers:
        - name: {{ template "geomapfish.fullname" $root }}-{{ $key }}
          image: {{ $root.Values.registry.host }}/{{ $root.Values.registry.namespace }}/{{ template "geomapfish.name" $root }}-{{ $key }}:{{ $root.Values.imageTag }}
          ports:
          - containerPort: {{ $value.targetPort }}
    {{- if $value.dbEnvs }}
      {{- include "geomapfish.pod_envs" $root | indent 10 }}
    {{- end }}
          resources: {}
        restartPolicy: Always
    test: false
    triggers:
    - type: ConfigChange
  {{- end }}
kind: List
{{- end }}