{{- if eq .Values.clusterType "openshift" -}}
apiVersion: {{ template "geomapfish.api_version" . }}
kind: Route
metadata:
  name: {{ template "geomapfish.fullname" . }}-wsgi
  labels:
    {{- include "geomapfish.release_labels" . | indent 4 }}
spec:
  to:
    kind: Service
    name: {{ template "geomapfish.fullname" . }}-wsgi
    weight: 100
  wildcardPolicy: None
{{- end }}