{{ $root := . }}
apiVersion: v1
items:
{{- range $key, $value := .Values.apps }}
- apiVersion: v1
  kind: Service
  metadata:
    name: {{ template "geomapfish.fullname" $root }}-{{ $key }}
    labels:
      {{- include "geomapfish.release_labels" $root | indent 6 }}
  spec:
    ports:
    - name: "{{ $value.port }}"
      port: {{ $value.port }}
      protocol: {{ $value.protocol }}
      targetPort: {{ $value.targetPort }}
    selector:
      name: {{ template "geomapfish.fullname" $root }}-{{ $key }}
{{- end }}
kind: List
