apiVersion: v1
kind: BuildConfig
metadata:
  namespace: geomapfish-cicd
  creationTimestamp: null
  labels:
    build: demo-geomapfish-pipeline-master
  name: demo-geomapfish-pipeline-master
spec:
  nodeSelector: null
  output: {}
  postCommit: {}
  resources: {}
  source:
    git:
      uri: https://github.com/camptocamp/demo-geomapfish-openshift.git
      ref: master
    type: Git
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
    type: JenkinsPipeline
  triggers:
  - github:
      secret: LmXMteYIiO7gqUH3cM2B
    type: GitHub
  - generic:
      secret: IQ7g393nJfjQNpiU0hsr
    type: Generic
