# Default values for geomapfish chart
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

author: "marc.sutterATcamptocamp.com"

# target cluser ('openshift' or 'kubernetes')
# this will adjust the apiVersion to 'openshift.org/v1' in openshft
# only templates
# More infos on this: https://github.com/megalord/openshift-api-group
clusterType: openshift

imageTag: latest

# this replica is valid for the wsgi service/pod
replicas: 1

registry:
  host: 172.30.26.108
  port: 5000
  namespace: geomapfish-cicd

db:
  type: postgresql
  port: 5432
  user: www-data
  pass: www-data
  host: geomapfish-demo.camptocamp.net
  osm_db: osm
  gmf_db: demo_openshift_2_2

apps:
  wsgi:
    port: 8480
    protocol: TCP
    targetPort: 80
    replicas: 1
    dbEnvs: true
  print:
    port: 8280
    protocol: TCP
    targetPort: 8080
    replicas: 1
  mapserver:
    port: 8380
    protocol: TCP
    targetPort: 80
    replicas: 1
