apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    build: openshift-jenkins-slave-geomapfish
  name: openshift-jenkins-slave-geomapfish
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: openshift-jenkins-slave-geomapfish:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/camptocamp/demo-geomapfish-openshift.git
    contextDir: "openshift/build/jenkins-slave-geomapfish" 
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: geomapfish_build:jenkins
    type: Docker
  triggers:
  - github:
      secret: 34Qbhk8evOxvOXIuDKuB
    type: GitHub
  - generic:
      secret: Wvggb-nh7TM-N4-A9pr6
    type: Generic
  - type: ConfigChange
