apiVersion: v1
kind: BuildConfig
metadata:
  namespace: geomapfish-cicd
  annotations:
    openshift.io/generated-by: OpenShiftNewBuild
  creationTimestamp: null
  labels:
    build: demo-geomapfish
  name: demo-geomapfish
spec:
  nodeSelector: null
  output: {}
  postCommit: {}
  resources: {}
  source:
    git:
      uri: https://github.com/camptocamp/demo-geomapfish-openshift.git
    type: Git
  strategy:
    jenkinsPipelineStrategy: {}
    type: JenkinsPipeline
  triggers:
  - github:
      secret: LmXMteYIiO7gqUH3cM2B
    type: GitHub
  - generic:
      secret: IQ7g393nJfjQNpiU0hsr
    type: Generic
  - type: ConfigChange
