apiVersion: v1
items:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp: null
    labels:
      build: demo-geomapfish
    name: demo-geomapfish
  spec:
    nodeSelector: null
    output: {}
    postCommit: {}
    resources: {}
    source:
      git:
        ref: openshift
        uri: https://github.com/camptocamp/demo_geomapfish.git
      type: Git
    strategy:
      jenkinsPipelineStrategy: {}
      type: JenkinsPipeline
    triggers:
    - github:
        secret: LmXMteYIiO7gqUH3cM2B
      type: GitHub
    - generic:
        secret: IQ7g393nJfjQNpiU0hsr
      type: Generic
    - type: ConfigChange
  status:
    lastVersion: 0
kind: List
metadata: {}