apiVersion: v1
kind: BuildConfig
metadata:
  namespace: geomapfish-cicd
  labels:
    build: demo-geomapfish-wsgi
  name: demo-geomapfish-wsgi
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: demo-geomapfish-wsgi:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/camptocamp/demo-geomapfish-openshift.git
    type: Git
  strategy:
    dockerStrategy: {}
    type: Docker
  triggers:
  - github:
      secret: x9DoOG5jUoZFGhQtOzSC
    type: GitHub
  - generic:
      secret: EDFBv2r2raCkYty296o9
    type: Generic
status:
  lastVersion: 0
