apiVersion: v1
items:
- apiVersion: project.openshift.io/v1
  kind: Project
  metadata:
    annotations:
      openshift.io/description: Geomapfish PRD
      openshift.io/display-name: geomapfish-prd
    creationTimestamp: null
    name: geomapfish-prd
  spec: {}
  status: {}
- apiVersion: authorization.openshift.io/v1
  groupNames:
  - system:serviceaccounts:geomapfish-prd
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    name: system:image-pullers
    namespace: geomapfish-prd
  roleRef:
    name: system:image-puller
  subjects:
  - kind: SystemGroup
    name: system:serviceaccounts:geomapfish-prd
  userNames: null
- apiVersion: authorization.openshift.io/v1
  groupNames: null
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    name: system:image-builders
    namespace: geomapfish-prd
  roleRef:
    name: system:image-builder
  subjects:
  - kind: ServiceAccount
    name: builder
  userNames:
  - system:serviceaccount:geomapfish-prd:builder
- apiVersion: authorization.openshift.io/v1
  groupNames: null
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    name: system:deployers
    namespace: geomapfish-prd
  roleRef:
    name: system:deployer
  subjects:
  - kind: ServiceAccount
    name: deployer
  userNames:
  - system:serviceaccount:geomapfish-prd:deployer
- apiVersion: authorization.openshift.io/v1
  groupNames: null
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    name: admin
    namespace: geomapfish-prd
  roleRef:
    name: admin
  subjects:
  - kind: User
    name: admin
  userNames:
  - admin
kind: List
metadata: {}
resourceVersion: ""
selfLink: ""